[server]
maxUploadSize = 50
maxMessageSize = 400
enableWebsocketCompression = true

[theme]
base                     = "light"
primaryColor             = "#fd4816"
backgroundColor          = "#ffffff"
secondaryBackgroundColor = "#f7f7f8"
textColor                = "#1a1a1a"
font                     = "sans serif"
